services:
    order:
        container_name: order_microservice
        image: order_microservice-service
        build:
            context: .
            dockerfile: ./Dockerfile
        restart: unless-stopped
        ports:
             - "7072:80"
        networks:
             - core
        expose:
             - "80"

networks:
  core:
    external: true