services:
    delivery:
        container_name: delivery_microservice
        image: delivery_microservice-service
        build:
            context: .
            dockerfile: ./Dockerfile
        restart: unless-stopped
        ports:
             - "7073:80"
        networks:
             - core
        expose:
             - "80"

networks:
  core:
    external: true